#!/bin/sh 

if [[ ! $(xset -q) ]]; then
  return 1 #X server could not be found
fi

# Source our functions
. /usr/local/share/trueos/scripts/functions.sh

if [ -e "/root/.xprofile" ]
then
. /root/.xprofile
fi

# Setting a language
if [ -e "/etc/trueos-lang" ] ; then
   LANG=`cat /etc/trueos-lang`
   export LANG
fi

touch ${XGUITMP}/.xstartupsuccess
/usr/local/bin/startfluxbox &
PID=$!
/usr/local/bin/pc-xgui -test
if [ $? -eq 0 ]; then
  touch ${XGUITMP}/.selected

  # Run the firstboot script immediately
 run_firstboot
fi
kill -9 ${PID}
