#!/bin/sh 

if [[ ! $(xset -q) ]]; then
  return 1 #X server could not be found
fi

# Set all our path variables
PATH="/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/usr/local/sbin"
export PATH

if [ -e "/root/.xprofile" ]
then
. /root/.xprofile
fi

# Setting a language
if [ -e "/etc/trueos-lang" ] ; then
   LANG=`cat /etc/trueos-lang`
   export LANG
fi
 
touch ${XGUITMP}/.xstartupsuccess
/usr/local/bin/startfluxbox &
PID=$!
/usr/local/bin/pc-xgui
if [ "$?" = "1" ]
then
 echo "Canceled" > ${XGUITMP}/.canceled
fi
kill -9 ${PID}
